name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-1
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        env:
          TF_VAR_ami_id: ${{ secrets.AMI_ID }}
        run: terraform plan -out=tfplan
      
      - name: Comment plan result
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          terraform show -no-color tfplan | gh pr comment ${{ github.event.pull_request.number }} -F -

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        env:
          TF_VAR_ami_id: ${{ secrets.AMI_ID }}
        run: terraform apply -auto-approve tfplan